#断路器原理
通常情况下，程序会通过网络远程调用运行在其他处理器或者其他服务器上的程序。远程调用和本地调用的一个最大的区别就是前者有可能会失败，或者被挂起直到超时。更糟糕的是，如果你对一个反应迟钝的服务发起多个请求，那么你可能会耗尽关键资源，导致跨多个系统的级联故障。**Circuit Breaker**, 断路器就是为了解决这一问题而生。
>远程调用失败/超时导致一系列的问题，在错综复杂的服务调用网中，如果不能识别出调用失败和做相应的处理的话，很可能导致多个系统的级联故障。

断路器的基本思路非常简单。将受保护的功能调用封装在一个断路器对象中，用于监视故障。一旦故障次数达到一定的阈值，断路器跳闸，对于所有后面进来的请求，断路器将返回一个错误，没有请求会被发起。通常情况下，你也会需要监控断路器跳闸的情况。

![断路器基本原理](http://martinfowler.com/bliki/images/circuitBreaker/sketch.png)

以下是一个例子：

~~~ruby
cb = CircuitBreaker.new {|arg| @supplier.func arg}
~~~

CircuitBreaker是一个断路器类（储存了timeout、失败阈值、监视器等信息）

~~~ruby
class CircuitBreaker...
  attr_accessor :invocation_timeout, :failure_threshold, :monitor
  def initialize &block
    @circuit = block
    @invocation_timeout = 0.01
    @failure_threshold = 5
    @monitor = acquire_monitor
    reset
  end
~~~

当断路器关闭时，调用call方法会调用到底层封装的服务。
当断路器打开时，调用则会返回一个错误。

~~~ruby
# client code
    aCircuitBreaker.call(5)


class CircuitBreaker...
  def call args
    case state
    when :closed
      begin
        do_call args
      rescue Timeout::Error
        record_failure
        raise $!
      end
    when :open then raise CircuitBreaker::Open
    else raise "Unreachable Code"
    end
  end
  def do_call args
    result = Timeout::timeout(@invocation_timeout) anddo
      @circuit.call args
    end
    reset
    return result
  end
~~~

超时调用的话计数器就加1，调用成功则清零：

~~~ruby
class CircuitBreaker...
  def record_failure
    @failure_count += 1
    @monitor.alert(:open_circuit) if :open == state
  end
  def reset
    @failure_count = 0
    @monitor.alert :reset_circuit
  end
~~~

失败的次数与阈值决定了断路器的状态

~~~Ruby
class CircuitBreaker...
  def state
     (@failure_count >= @failure_threshold) ? :open : :closed
  end
~~~

上面这个简单的断路器避免了当断路器打开的时候发起请求，但当服务恢复正常后，还需额外的干预来重置断路器的状态。在建筑中使用了电断路器来解决这一问题，但对于程序来说，断路器可以可以自检测服务是否可用。这种自恢复的断路器，可以使用轮询的方式来实现。

![自恢复断路器](http://martinfowler.com/bliki/images/circuitBreaker/state.png)

创建这种类型的断路器意味着添加一个重试阈值和设置一个变量来存持最后一个错误的时间。

~~~ruby
class ResetCircuitBreaker...
  def initialize &block
    @circuit = block
    @invocation_timeout = 0.01
    @failure_threshold = 5
    @monitor = BreakerMonitor.new
    @reset_timeout = 0.1
    reset
  end
  def reset
    @failure_count = 0
    @last_failure_time = nil
    @monitor.alert :reset_circuit
  end
~~~

新增了第三个状态，半打开(Half-Open)状态，意味着断路器可以尝试发起请求来看看问题是否已经解决。

~~~ruby
class ResetCircuitBreaker...
  def state
    case
    when (@failure_count >= @failure_threshold) && 
        (Time.now - @last_failure_time) > @reset_timeout
      :half_open
    when (@failure_count >= @failure_threshold)
      :open
    else
      :closed
    end
  end
~~~

在半打开状态实验性地发起请求，如果请求成功则重置断路器，如果请求失败，则重启超时。

~~~ruby
class ResetCircuitBreaker...
  def call args
    case state
    when :closed, :half_open
      begin
        do_call args
      rescue Timeout::Error
        record_failure
        raise $!
      end
    when :open
      raise CircuitBreaker::Open
    else
      raise "Unreachable"
    end
  end
  def record_failure
    @failure_count += 1
    @last_failure_time = Time.now
    @monitor.alert(:open_circuit) if :open == state
  end
~~~

并不是所有的错误都会导致断路器打开，比如一些业务异常。

远程调用相对比较耗时，当你发起很多请求的时候有可能会造成等待（交通堵塞）。 所以一个比较好的做法是把不同的请求放在不同的线程内调用，并采用 future-promise模式来处理请求结果。如果采用线程池，但线程池耗尽时，可以把断路器设置成打开状态。

这个例子中采用简单的失败次数来决定断路器打开的阈值。一些更复杂的需求可能要根据请求的成功率来判定断路器的状态，比如成功率在50%以上。另外不同错误也可能有不同的阈值，比如超时10，连接错误3等。

这个例子的请求发起的是同步请求，但断路器也可以用在异步请求中。比较常见的技术时，把请求放在消息队列上，当队列满的时候打开断路器。

一般来说断路器是有价值的，但使用它们的客户需要对断路器故障作出反应。和任何远程调用一样，你需要考虑在失败的情况下做什么。比如：一个信用卡授权可以放在一个队列处理；获取不到数据可以先展示一个可靠的老数据。

